kind: Deployment
apiVersion: apps/v1
metadata:
  name: jpetstoreweb
spec:
  replicas: 1
  selector:
      matchLabels:
        app: jpetstoreweb
  template:
    metadata:
      labels:
        app: jpetstoreweb
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: jpetstoreweb
        image: <image-repository-name>/jpetstorefinal
        imagePullPolicy: Always
        env:
          - name: VERSION
            value: "1"
          - name: mysqlUrl
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: mysql.url
          - name: mysqlUser
            valueFrom:
                secretKeyRef:
                  name: mysql-creds
                  key: mysql.username
          - name: mysqlPass
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: mysql.password
        ports:
        - containerPort: 9080
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jpetstoreweb
  name: jpetstore
spec:
  type: LoadBalancer  # use LoadBalancer as type here
  ports:
    - port: 9080
  selector:
    app: jpetstoreweb
